name: ASDF CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  plugin-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python:
          - '3.9'
          - '3.13'
        version:
          - '2.7.1'  # earliest with .pyz asset
          - 'latest'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python }}
      # See https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md#example-github-action
      - name: test plugin
        uses: asdf-vm/actions/plugin-test@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
        with:
          command: pre-commit --version
          version: ${{ matrix.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0

      - name: pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --all --show-diff-on-failure --color=always


